# Generated by Django 4.2.7 on 2023-11-24 12:47
from __future__ import unicode_literals
from uuid import uuid4
from django.db import migrations
from katalog import models

from katalog.models import Kategori, Produk, Status
from utils import jsonkeobj

jsonkeobj.konvert()


def isiDB(apps, schema_editor):
    for kategori in jsonkeobj.isiKategori(jsonkeobj.daftar_objek):
        Kategori(nama_kategori=kategori).save()

    for status in jsonkeobj.isiStatus(jsonkeobj.daftar_objek):
        Status(nama_status=status).save()

    for j in jsonkeobj.daftar_objek:
        Produk(
            id_produk=int(j.id_produk),
            nama_produk=j.nama_produk,
            kategori=Kategori.objects.get(nama_kategori=j.kategori),
            harga=j.harga,
            status=Status.objects.get(nama_status=j.status),
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("katalog", "0001_initial"),
    ]

    operations = [migrations.RunPython(isiDB)]
