# Generated by Django 4.2.7 on 2023-11-24 12:47
from __future__ import unicode_literals
from django.db import migrations

from katalog.models import Kategori, Produk, Status
from utils import jsonkeobj
import json

jsonkeobj.konvert()
# datajson = jsonkeobj.daftar_objek
def isiDB(apps,skema):
    for i in jsonkeobj.daftar_objek:
        Kategori(nama_kategori=i.kategori).save()
        Status(nama_status=i.status).save()
        Produk(
            id_produk=i.id_produk,
            nama_produk=i.nama_produk,
            kategori=i.kategori,
            harga=i.harga,
            status=i.status,
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(isiDB)
    ]
