# Generated by Django 4.2.7 on 2025-01-28 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_auto_20231127_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.kategori'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.status'),
        ),
    ]
