version: "3.8"
services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  django:
    container_name: django
    image: masprast25/django_postgresql_produk
    ports:
      - 8000:8000
    environment:
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
    depends_on:
      - db

volumes:
  postgresdb:
