version: "3.8"
services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - docker.env
    volumes:
      - postgresdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=backendtes
      - POSTGRES_USER=backenduser
      - POSTGRES_PASSWORD=backendpass
  django:
    build: .

volumes:
  postgresdb:
