version: "3.8"
services:
  db:
    # image: postgres:16-alpine
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: always
    volumes:
      - postgresdb:/var/lib/postgresql/data
      # - ./docker/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - 5432:5432
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s

volumes:
  postgresdb:
